POST http://localhost:5500/usuarios
Content-type: application/json

{
    "nom": "prueba",
    "apellido": "prueba",
    "email": "prueba@gmail.com",
    "fecha_nac": "1983-02-09",
    "telefono": "0123456789",
    "cursos_interes": "HTML",
    "fk_nivel": "1",
    "passwordHash": "1234",
    "fk_rol": "1"
}